// generated by Fast Light User Interface Designer (fluid) version 1.0300
#include "main.h"
#include <iostream>
#include "osc.h"
#include "gui.h"
#include "leslie.h"
#ifndef ENABLE_GUI
#include <unistd.h>
#endif

using namespace std;

#ifdef ENABLE_GUI
void GUIRateChange(Widget* widget)
{
    leslie->setRate(((Valuator*)widget)->value());
}

void GUIAmpChange(Widget* widget)
{
    leslie->setAmp(((Valuator*)widget)->value());
}

void GUIModChange(Widget* widget)
{
    leslie->setMod(((Valuator*)widget)->value());
}

void GUIPhaseChange(Widget* widget)
{
    leslie->setPhase(((Valuator*)widget)->value());
}

void GUIEnableClick(Widget* widget)
{
    leslie->setEnable(((Switch*)widget)->value());
}
#endif

int main(int argc, char **argv) {

#ifdef ENABLE_GUI
    Valuator* v;

    v=new VSlider();
    v->setCoords(0.1,0.1,0.2,0.8);
    v->Max(LESLIE_RATE_MAX);
    v->Min(LESLIE_RATE_MIN);
    v->value(LESLIE_DEF_RATE);
    v->Caption("Rate");
    v->sigClick.connect(GUIRateChange);
    v->sigDrag.connect(GUIRateChange);
    GUI::widget.push_back(v);

    v=new VSlider();
    v->setCoords(0.4,0.1,0.2,0.8);
    v->Max(LESLIE_AMP_MAX);
    v->Min(LESLIE_AMP_MIN);
    v->value(LESLIE_DEF_AMP);
    v->Caption("Amp");
    v->sigClick.connect(GUIAmpChange);
    v->sigDrag.connect(GUIAmpChange);
    GUI::widget.push_back(v);

    v=new VSlider();
    v->setCoords(0.7,0.1,0.2,0.8);
    v->Max(LESLIE_MOD_MAX);
    v->Min(LESLIE_MOD_MIN);
    v->value(LESLIE_DEF_MOD);
    v->Caption("Mod");
    v->sigClick.connect(GUIModChange);
    v->sigDrag.connect(GUIModChange);
    GUI::widget.push_back((Widget*)v);

    v=new VSlider();
    v->setCoords(1.0,0.1,0.2,0.8);
    v->Max(LESLIE_PHASE_MAX);
    v->Min(LESLIE_PHASE_MIN);
    v->value(LESLIE_DEF_PHASE);
    v->Caption("Phase");
    v->sigClick.connect(GUIPhaseChange);
    v->sigDrag.connect(GUIPhaseChange);
    GUI::widget.push_back(v);

    Toggle* s=new Toggle();
    s->setCoords(1.3,0.7,0.2,0.2);
    s->Caption("Enable");
    s->sigClick.connect(GUIEnableClick);
    s->value(LESLIE_DEF_ENABLE);
    GUI::widget.push_back(s);

    GUI::init(argc,argv);
#endif

    OSC* osc=&OSC::getInstance();

#ifdef ENABLE_GUI
    GUI::run();
#else
	while(1) { sleep(1); }
#endif
}
